[workspace]
resolver = "2"
members = [
    "examples/",
    "rend3",
    "rend3-anim",
    "rend3-egui",
    "rend3-framework",
    "rend3-gltf",
    "rend3-routine",
    "rend3-test",
    "rend3-types",
]

[profile.ci]
inherits = "dev"
debug = false
incremental = false

[profile.ci.package."*"]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
lto = "thin"

#   Override egui - doesn't work.
[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", branch = "master"}
egui-wgpu = { git = "https://github.com/emilk/egui", branch = "master"}
epaint = { git = "https://github.com/emilk/egui", branch = "master"}
## wgpu = { version = "22.1" }
